### ISSUE TITLE
Broken repository URL on npm

### ISSUE THREAD

**Issue by zenorocha** [zalando-incubator/zoll#1]
<img width="358" alt="screen shot 2016-06-11 at 2 16 47 pm" src="https://cloud.githubusercontent.com/assets/398893/15987505/2fcd3860-2fdf-11e6-816d-1019db636dfc.png">

**Comment by vigneshshanmugam** [comment]
@zenorocha Thanks for reporting. Sorry for the delay. 

should be fixed now.
